// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaEXOmTT-WKo5KhbL7-wJCZ_4CSheThzM',
    appId: '1:843877756096:android:a2ac9f0126d390e33ed125',
    messagingSenderId: '843877756096',
    projectId: 'flutter-takim67',
    databaseURL: 'https://flutter-takim67-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-takim67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKZCmwr9lHbTCKD3GeboQOT5_1pP2Iko',
    appId: '1:843877756096:ios:2ece31b0a40e1a323ed125',
    messagingSenderId: '843877756096',
    projectId: 'flutter-takim67',
    databaseURL: 'https://flutter-takim67-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-takim67.appspot.com',
    androidClientId: '843877756096-rfgtrj3aqbhps3okne9mc40h212pibqr.apps.googleusercontent.com',
    iosClientId: '843877756096-c3nm38pgdcnrebhqefvgmil4utcs55am.apps.googleusercontent.com',
    iosBundleId: 'com.example.randomizeelement12',
  );
}
